# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecee35e76f7d909839d5a7a9ccecbfbc36b917d77fe54c67f185c272c12297ebdb618c26ea03746992015d4dfc5f548be765994ffb62726f33055de82a1aef17

test:
  secret_key_base: 18f0b7f7f780bab4c61e7820a503f05e8d178f6fd789be92fb941871489f89e5fcba168c60ea7bbd89e075b74b255604fc4e10718bc5ff447e24d0a287de2f2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
